#!/bin/bash

LOKASI="$(basename "$PWD")"

clear
rm baca.html

echo '<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="initial-scale=1, width=device-width" />
    <title>'$LOKASI' - Baca Komik - Dibuat oleh Muhammad Zaini .com</title>
    <style>
	* {
		margin: 0;
		padding: 0;
	}
	img {
		width: 80%;
		display: block;
		margin: auto;
	}
	</style>
</head>

<body>' >> baca.html

if [ $1 == "jpg" ]
	then
		for i in *.jpg; do echo "<img src=\"$i\"/>" >> baca.html; done;
elif [ $1 == "png" ]
	then
		for i in *.png; do echo "<img src=\"$i\"/>" >> baca.html; done;
elif [ $1 == "jpeg" ]
	then
		for i in *.jpeg; do echo "<img src=\"$i\"/>" >> baca.html; done;
fi

echo '</body>

</html>
' >> baca.html

echo "Silahkan membaca :)"