#!/bin/bash

LOKASI="$(basename "$PWD")"

rm baca.html

echo '<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="initial-scale=1, width=device-width" />
    <title>'$LOKASI' - Baca Komik - Dibuat oleh Muhammad Zaini .com</title>
    <style>
	* {
		margin: 0;
		padding: 0;
	}
	img {
		width: 80%;
		display: block;
		margin: auto;
	}
	</style>
</head>

<body>' >> baca.html

for i in *; do echo "<img src='$i' alt=''/>" >> baca.html; done;

echo '</body>

</html>
' >> baca.html

echo "Silahkan membaca :)"